version: "2.3"

services:
  test:
    image: gone/php:cli-7.4
    volumes:
      - ./:/app
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: testuser
      MYSQL_PASSWORD: m4&ChangeMe^eN
      MYSQL_DATABASE: blog

  redis:
    image: redis

  mysql:
    image: benzine/mariadb:10.4
    environment:
      MYSQL_ROOT_PASSWORD: ChangeMe
      MYSQL_USER: testuser
      MYSQL_PASSWORD: m4&ChangeMe^eN
      MYSQL_DATABASE: blog
    ports:
      - 127.0.0.1:3306:3306